---
title: "Design space"
output: 
  flexdashboard::flex_dashboard:
runtime: shiny
---


```{r global, include=FALSE}

options(stringsAsFactors=FALSE)
while(dev.next()>1) dev.off()
rm(list=objects())
gc()

libs <- c("shiny", "plotly")
x <- sapply(libs, function(x) {if(!require(x, character.only = T)) install.packages(x)})
x <- sapply(libs, function(x) {require(x, character.only = T)})

setwd("C:/MyDesktop/_My Reference/_My Notes")
set.seed(1000)

```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
sliderInput("x1_range", label = "X1 range",
            min = 1, max = 20, value = 10, step = 1)

sliderInput("x2_range", label = "X2 range",
            min = 1, max = 20, value = 10, step = 1)

selectInput("f_form", label = "Function Relationship",
            choices = c("Linear", "Linear - Interaction", "Quadratic", "God knows"), 
            selected = "Linear")

sliderInput("noise", label = "Sampling noise/uncertainty",
            min = 0, max = 1, value = 0, step = 0.1)


```



Column
-----------------------------------------------------------------------

```{r}

renderPlotly({
  
  x1_range <- input$x1_range
  x2_range <- input$x2_range
  f_form <- input$f_form
  noise <- input$noise

  x1 <- seq(0, x1_range, by = 0.5)
  x2 <- seq(0, x2_range, by = 0.5)
  
  if (f_form == "Linear") {
    f <- function(x1, x2) {1 + 5*x1 + 3*x2}
  } else if (f_form == "Linear - Interaction") {
    f <- function(x1, x2) {1 + 5*x1 + 3*x2 + x1*x2}
  } else if (f_form == "Quadratic") {
    f <- function(x1, x2) {1 + 2*(x1-5)**2 + 3*(x2-2)**2}
  } else if (f_form == "God knows") {
    f <- function(x1, x2) {(x1-5)**3 - 3*(x1-5)*(x2-2)**2}
  }


  x1_select <- c(x1_range/5, x1_range/2, 4*x1_range/5)
  x2_select <- c(x2_range/5, x2_range/2, 4*x2_range/5)
  y_select <- outer(x1_select, x2_select, f)
  select <- data.frame(x1 = rep(x1_select, each = length(x2_select)),
                       x2 = rep(x2_select, length(x1_select)),
                       y = c(y_select))
  select_one <- select
  for (i in 1:3) {
    add <- select_one
    add$y <- add$y*(1+rnorm(1, mean = 0, sd = noise))
    select <- rbind(select, add)
  }

  y <- outer(x1, x2, f)
  plot_ly(z = y, x = x1, y = x2, type = 'surface', 
          width = 700, height = 600) %>% 
    add_markers(z = select$y, x = select$x1, y = select$x2, type = "scatter3d") %>% 
    layout(title = f_form,
           autorange = F, aspectmode = 'manual', 
           scene = list(xaxis = list(title = "X1"),
                        yaxis = list(title = "X2"),
                        zaxis = list(title = "y"),
                        aspectratio = list(x = 1, y = 1, z = 1)))
    
})

```




